version: 2.1

orbs:
  azure-cli: circleci/azure-cli@1.1.0
  slack: circleci/slack@4.1.4

jobs:
  build-push:
    executor: azure-cli/default
    steps:
      - azure-cli/install
      - azure-cli/login-with-service-principal
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t sinatrasample.azurecr.io/sinatra-sample:$CIRCLE_SHA1 .
      - run:
          name: Push Docker image
          command: |
            docker login $ACR_REPOSITORY -u $ACR_LOGIN -p $ACR_PASSWORD
            docker push $ACR_REPOSITORY/sinatra-sample:$CIRCLE_SHA1
            az webapp config container set -c "$ACR_REPOSITORY/sinatra-sample:$CIRCLE_SHA1" -p $ACR_PASSWORD -r https://$ACR_REPOSITORY -u $ACR_LOGIN -n $AZURE_APP_NAME -s staging -g $AZURE_RESOURCE_GROUP
  swap:
    executor: azure-cli/azure-docker
    steps:
      - azure-cli/login-with-service-principal
      - run:
          name: Slot swap
          command: |
            az webapp deployment slot swap -g $AZURE_RESOURCE_GROUP -n $AZURE_APP_NAME --slot staging

workflows:
  version: 2
  deploy:
    jobs:
      - build-push:
          filters:
            branches:
              only:
                - main
      - slack/on-hold:
          requires:
            - build-push
      - approval:
          type: approval
          requires:
            - slack/on-hold
      - swap:
          requires:
            - approval
